// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HousingPricePredML.Model
{
    public class ModelInput
    {
        [ColumnName("tip_proprietate"), LoadColumn(0)]
        public string TipProprietate { get; set; }


        [ColumnName("nr_camere"), LoadColumn(1)]
        public float NrCamere { get; set; }


        [ColumnName("suprafata"), LoadColumn(2)]
        public float Suprafata { get; set; }


        [ColumnName("suprafata_teren"), LoadColumn(3)]
        public float SuprafataTeren { get; set; }


        [ColumnName("an_constructie"), LoadColumn(4)]
        public float AnConstructie { get; set; }


        [ColumnName("zona"), LoadColumn(5)]
        public string Zona { get; set; }
    }
}
