// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HousingPricePredictionProjectML.Model
{
    public class ModelInput
    {
        [ColumnName("tip_proprietate"), LoadColumn(0)]
        public string Tip_proprietate { get; set; }


        [ColumnName("nr_camere"), LoadColumn(1)]
        public float Nr_camere { get; set; }


        [ColumnName("suprafata"), LoadColumn(2)]
        public float Suprafata { get; set; }


        [ColumnName("suprafata_teren"), LoadColumn(3)]
        public float Suprafata_teren { get; set; }


        [ColumnName("an_constructie"), LoadColumn(4)]
        public float An_constructie { get; set; }


        [ColumnName("zona"), LoadColumn(5)]
        public string Zona { get; set; }


        [ColumnName("pret"), LoadColumn(6)]
        public float Pret { get; set; }


    }
}
