// This file was auto-generated by ML.NET Model Builder. 

using System;
using HousingPricePredML.Model;

namespace HousingPricePredML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                TipProprietate = @"APT",
                NrCamere = 3F,
                Suprafata = 65F,
                SuprafataTeren = 65F,
                AnConstructie = 1985F,
                Zona = @"tudor-vladimirescu",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Pret with predicted Pret from sample data...\n\n");
            Console.WriteLine($"Tip_proprietate: {sampleData.TipProprietate}");
            Console.WriteLine($"Nr_camere: {sampleData.NrCamere}");
            Console.WriteLine($"Suprafata: {sampleData.Suprafata}");
            Console.WriteLine($"Suprafata_teren: {sampleData.SuprafataTeren}");
            Console.WriteLine($"An_constructie: {sampleData.AnConstructie}");
            Console.WriteLine($"Zona: {sampleData.Zona}");
            Console.WriteLine($"\n\nPredicted Pret: {predictionResult.Score}\n\n");

        }
    }
}
