// This file was auto-generated by ML.NET Model Builder. 

using System;
using HousingPricePredictionProjectML.Model;

namespace HousingPricePredictionProjectML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Tip_proprietate = @"APT",
                Nr_camere = 3F,
                Suprafata = 65F,
                Suprafata_teren = 65F,
                An_constructie = 1985F,
                Zona = @"tudor-vladimirescu",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Pret with predicted Pret from sample data...\n\n");
            Console.WriteLine($"Tip_proprietate: {sampleData.Tip_proprietate}");
            Console.WriteLine($"Nr_camere: {sampleData.Nr_camere}");
            Console.WriteLine($"Suprafata: {sampleData.Suprafata}");
            Console.WriteLine($"Suprafata_teren: {sampleData.Suprafata_teren}");
            Console.WriteLine($"An_constructie: {sampleData.An_constructie}");
            Console.WriteLine($"Zona: {sampleData.Zona}");
            Console.WriteLine($"\n\nPredicted Pret: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
